import { Amplify } from 'aws-amplify';

// amplify_outputs.json is generated by `yarn sandbox` or `yarn deploy` from the backend.
// Copy/symlink it here before running the app.
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const outputs = require('../../amplify_outputs.json');
  Amplify.configure(outputs);
} catch {
  console.warn(
    '[Amplify] amplify_outputs.json not found. ' +
      'Run `yarn sandbox` in investorsplaygroundbackend and copy the output file here.'
  );
}
